# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomNo', models.IntegerField()),
                ('Occupancy', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contactno', models.IntegerField()),
            ],
        ),
    ]
