# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('date', models.DateField()),
                ('bookedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Time',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Room'),
        ),
    ]
