# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20160306_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='startTime',
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='room',
            name='Type',
            field=models.CharField(max_length=30),
        ),
    ]
