# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20160306_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Type',
            field=models.IntegerField(choices=[('1', 'Projector'), ('2', 'Video Conferencing')], default='1'),
        ),
    ]
