# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20160306_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='CourseNo',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='room',
            name='Type',
            field=models.IntegerField(choices=[(1, 'Projector'), (2, 'Video Conferencing')], default=1),
        ),
    ]
