# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_auto_20160306_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Faculty')], default=1),
        ),
    ]
