# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_booking_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_sem',
            name='bookedBy',
        ),
        migrations.RemoveField(
            model_name='booking_sem',
            name='room',
        ),
        migrations.DeleteModel(
            name='Booking_sem',
        ),
    ]
