# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_auto_20160307_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_sem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=11)),
                ('day', models.IntegerField()),
                ('CourseNo', models.CharField(default='', max_length=11)),
                ('bookedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.User')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.Room')),
            ],
        ),
    ]
